include:
  - ../frontend-legacy/docker-compose.yml
  - ../platform/docker-compose.yml
services:
  cluster_tests:
    image: helium/cluster-tests
    env_file: .env
    network_mode: "host"
    depends_on:
      - frontend
      - api
      - worker
